import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  // const [clevertapModule, setClevertapModule] = useState(null);

  // useEffect(() => {
  //   const fetchData = async () => {
  //     try {
  //       // Fetch data only on the client side
  //       const response = await fetch('/clevertap/upload', {
  //         method: 'POST',
  //         headers: {
  //           'X-CleverTap-Account-Id': 'W9R-486-4W5Z',
  //           'X-CleverTap-Passcode': '96921fadbf3445a7b416039d0e9d046d',
  //           'Content-Type': 'application/json',
  //         },
  //         body: JSON.stringify(profileData)
  //       });

  //       if (!response.ok) {
  //         throw new Error('Network response was not ok');
  //       }

  //       const data = await response.json();
  //       console.log(data);
  //     } catch (error) {
  //       console.error('Error:', error);
  //     }
  //   };

  //   // Check if the code is running on the client side
  //   if (typeof window !== 'undefined') {
  //     clevertapInit();
  //     fetchData();
  //   }
  // }, []);

  // const clevertapInit = async () => {
  //   // Check if CleverTap module is already initialized
  //   let clevertap = clevertapModule;
  //   if (!clevertap) {
  //     clevertap = await import('clevertap-web-sdk/clevertap');
  //     clevertap.default.init("ZWW-WWW-WWRZ");
  //     clevertap.default.privacy.push({ optOut: false });
  //     clevertap.default.privacy.push({ useIP: false });
  //     clevertap.default.setLogLevel(3);
  //     setClevertapModule(clevertap.default);
  //   }

  //   if (clevertap) {
  //     clevertap.event.push('CM 3333'); // Popup Campaign
  //     clevertap.event.push('webpopup test'); // Banner Campaign
  //     clevertap.event.push('InternalTest2'); // Inbox Campaign
  //   }
  // };

  // const profileData = {
  //   "d": [
  //     {
  //       "identity": "345543",
  //       "type": "profile",
  //       "profileData": {
  //           "Name": "John Doe",
  //           "Email": "john03aug@abc.com"
  //       }
  //     }
  //   ]
  // };

  return (
    <>
    {/* <clevertap/> */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
          <div>
          <Link href="/contact">About Us</Link>
            {/* <button onClick={}> Contact Us</button> */}
          </div>
        </div>
      </main>
      
    </>
  )
}
